### PR TITLE
Fixing 'available' typo in log message

### PR DESCRIPTION
**Pull request by dubrie**
Log message was misspelling 'available' which was throwing off some parsing scripts.

### CODE REVIEW

**Review by sallylsy — APPROVED** [review]

**Review by sallylsy — APPROVED** [review]

**Comment by tomek-US** [comment]
please rebase to unblock merging

**Comment by dubrie** [comment]
@tomek-US merge branch should be updated to latest master now

**Review by tomek-US — APPROVED** [review]
LGTM

**Review by tomek-US — APPROVED** [review]
LGTM

**Pull request merged**
