### PR TITLE
Transformer infra enhancements and bug fixes

### PR DESCRIPTION
**Pull request by amrutasali**
Transformer infra enhancements & bug-fixes  :
- Sonic yang request default value handling
- Add nil check before accessing parentXpathData during yangSpecMap creation
- Handle Get validate handler evaluation for a child node and not set it to sibling via parent-node being reset at child node level.
- When creating sonic yang list key from DB key string don't split the key if the DB key string corresponds to a list having a single key-element.
- Support Partial key handling at whole list.

Verification done using unit tests on transformer test yang and added new cases for above.
Unit test run results are part of pipeline test run.

### CODE REVIEW

**Review by kwangsuk — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@amrutasali  can you please help to add the code PRs into this HLD PR? Thanks.

**Comment by jeff-yin** [comment]
> @amrutasali can you please help to add the code PRs into this HLD PR? Thanks.

There's no HLD in this PR. This PR consists of some bugfixes and performance enhancements, not behavioral changes. 
This PR link has been added to the Project Issue: https://github.com/sonic-net/SONiC/issues/1463

**Review by anand-kumar-subramanian — APPROVED** [review]

**Comment by skg-net** [comment]
@amrutasali Can you please update the Quality Metric (Alpha/Beta/GA) for the feature either in this PR comments or in HLD itself based on https://github.com/sonic-net/SONiC/blob/master/doc/SONiC%20feature%20quality%20definition.md
Thanks

**Comment by amrutasali** [comment]
> @amrutasali Can you please update the Quality Metric (Alpha/Beta/GA) for the feature either in this PR comments or in HLD itself based on https://github.com/sonic-net/SONiC/blob/master/doc/SONiC%20feature%20quality%20definition.md Thanks

Maturiy level – Alpha

•	Code PRs must come with unit tests (VS tests if applicable) aligned to code coverage: Yes
•	For standalone feature it is required to have enabled/disabled via config_db and set to disabled: N/A
•	Can go to master branch only: Yes
•	For feature based on ASIC vendor SAI implementation: SAI is not available yet: N/A
•	For feature based on Platform vendor API implementation: not available yet: N/A
•	Should not cause any degradation on available features. Need to run and ensure sonic-mgmt test suits is passing with no degradation: N/A
•	New sonic-mgmt test plan has been reviewed: N/A

**Pull request merged**
