### PR TITLE
Support a new ACL table type called L3V4V6.

### PR DESCRIPTION
**Pull request by rck-innovium**
Support a new ACL table type called L3V4V6.

This table supports both v4 and v6 Match types.

HLD: sonic-net/SONiC#1267

Signed-off-by: Ravi(Marvell) rck@innovium.com

### CODE REVIEW

**Comment by venkatmahalingam** [comment]
Please update the following file not the YANG file in sonic-mgmt-common repo.
https://github.com/sonic-net/sonic-buildimage/blob/5e6e2c827d4b937c06d3c31f85c22b99f50d0d5c/src/sonic-yang-models/yang-templates/sonic-types.yang.j2#L90

**Comment by rck-innovium** [comment]
> Please update the following file not the YANG file in sonic-mgmt-common repo. https://github.com/sonic-net/sonic-buildimage/blob/5e6e2c827d4b937c06d3c31f85c22b99f50d0d5c/src/sonic-yang-models/yang-templates/sonic-types.yang.j2#L90


https://github.com/sonic-net/sonic-buildimage/pull/14803

**Review by ayelrod — APPROVED** [review]

**Review by tomek-US — APPROVED** [review]
LGTM

**Comment by venkatmahalingam** [comment]
> @venkatmahalingam, is my understanding correct that your comment has been resolved?

I dont think the pull request is required as the changes are already merged using https://github.com/sonic-net/sonic-buildimage/pull/14803

**Comment by rck-innovium** [comment]
> > @venkatmahalingam, is my understanding correct that your comment has been resolved?
> 
> I dont think this pull request is required as the changes are already merged using [sonic-net/sonic-buildimage#14803](https://github.com/sonic-net/sonic-buildimage/pull/14803)

@venkatmahalingam  Thanks for pointing out that the yang models in the sonic-buildimage must be updated.  I want to understand why not keep sonic-mgmt-common in sync with the yang models in the sonic-buildimage?

**Comment by venkatmahalingam** [comment]
> > > @venkatmahalingam, is my understanding correct that your comment has been resolved?
> > 
> > 
> > I dont think this pull request is required as the changes are already merged using [sonic-net/sonic-buildimage#14803](https://github.com/sonic-net/sonic-buildimage/pull/14803)
> 
> @venkatmahalingam  Thanks for pointing out that the yang models in the sonic-buildimage must be updated.  I want to understand why not keep sonic-mgmt-common in sync with the yang models in the sonic-buildimage?

If you put the SONiC YANG model in sonic-mgmt-common, it will break some of the functionalities (e.g sonic-mgmt-common repo uses list with single entry for a global table whereas sonic-buildimage yang model uses singleton container) supported, we're working to use the sonic-buildimage YANG model for sonic-mgmt-common as well, until then let's not worry about common SONiC YANG models in both the repos.

**Comment by rck-innovium** [comment]
> If you put the SONiC YANG model in sonic-mgmt-common, it will break some of the functionalities (e.g sonic-mgmt-common repo uses list with single entry for a global table whereas sonic-buildimage yang model uses singleton container) supported, we're working to use the sonic-buildimage YANG model for sonic-mgmt-common as well, until then let's not worry about common SONiC YANG models in both the repos.

@venkatmahalingam Thanks for explaining. I'll close the PR.

**Pull request closed without merging**
